### ISSUE TITLE
Windows `-c --console` doesn't work in 2.5.0

### ISSUE THREAD

**Issue by nedtwigg** [karlsabo/packr#10]
It spawns a new console window (just like libgdx/master), but it doesn't print anything in it.  For comparison libgdx/master with `-c --console --verbose` will print something like:

```
Loading JVM runtime library ...
Passing VM options ...
  # -Xmx1G
Creating Java VM ...
Passing command line arguments ...
Loading JAR file ...
Adding 1 classpaths ...
  # lib/myapp.jar
Invoking static com.acmeApplication.main() function ...
```

**Comment by nedtwigg** [comment]
My guess is that 31463f0628ec288036776dfd95e1070d7155bd14 might be the source of the regression.

**Comment by nedtwigg** [comment]
I tried reverting 31463f0, and instead I now get no console at all.  So I have no idea where the problem is 🤷

**Comment by nedtwigg** [comment]
Btw, thanks very much for setting up this fork, please don't feel obligated to put effort into issues that I or others raise unless it's helpful to you also.  Having a CI setup where PRs can be tested and releases can be shared is a huge contribution :)

**Comment by karlsabo** [comment]
Yeah, it's a frustrating Windowism. For whatever historical reason win32 apps don't get a standard output stream 🙄. See https://stackoverflow.com/questions/191842/how-do-i-get-console-output-in-c-with-a-windows-program for more information.

As you discovered, the current --console seems to only work for the launched JVM and not any of the PackrLauncher output.

I'll take a look, this is something I tweaked a lifetime ago (2009 maybe?), before the days of GitHub. It might be off in my CVS repository.

To me the ideal solution would be a logging framework but pulling in 3rd party C/C++ libraries is a frustration I'm not willing to tackle at the moment.

**Comment by nedtwigg** [comment]
More info: PackrLauncher is successfully sending `cerr` to the console, it's just `cout` which is swallowed

**Comment by nedtwigg** [comment]
More info: PackrLauncher is successfully sending `cerr` and `cout` to the console, that part is working after all.  What's broken is that `--verbose` (and `-v`) are not parsed correctly, and verbose is actually never set to true.  Investigating...

**Comment by karlsabo** [comment]
The command line option parsing issue is caused by DrOpt being compiled with the "UNICODE" and "_UNICODE" macros. With those enabled DrOpt uses w_char.
Even w/ removing the UNICODE macros, I still don't get proper output from a command prompt (though the test run from Gradle now properly gets the output).

I'm also not sure what, if any repercussions there are to removing the UNICODE macros.

**Comment by nedtwigg** [comment]
Aha!  I have a user for whom the old libgdx/master doesn't work, and karlsabo/master is also not working for them.  I'm working through it, and one thing I'm trying right now is `wchar` paths...  If/when I learn anything I will report back, hopefully even with a PR!

**Comment by karlsabo** [comment]
Created a branch that uses wchar_t for all file operations and command line options for Windows. Give it a try and see how it goes:
https://github.com/karlsabo/packr/tree/dev/unicodePaths

There are a bunch of #ifdef everywhere. From everything I've read Windows code should always use UNICODE and wchar_t so I'll probably hardcode everything to that instead of there ever being a chance of compiling it as ANSI since there's no test for that and it's unlikely to ever work.

**Comment by karlsabo** [comment]
I pushed out a new release https://github.com/karlsabo/packr/releases/tag/2.6.0 that should resolve these issues (unicode file support and `--console`).

**Comment by nedtwigg** [comment]
Thanks!  I have a heavily hacked-up branch that I've been testing with someone who was having problems.  I'll sync-up anything I learn from that experiment with the changes you made (probably won't be anything to do :)

**Comment by karlsabo** [comment]
Thanks Ned, I'd love to have a PR for anything I missed or that you improve on.
